@startuml open_deposit

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

top to bottom direction

Person_Ext(client, "Клиент банка", "")
System_Ext(telecomOperator, "Телеком-оператор")
Person(back_employee, "Сотрудник бэк-офиса", "")

System_Boundary(bank, "Банк ''Открытие''") {
    Container(internet_bank, "Интернет-банк", "ASP.NET MVC 4.5 на основе .NET Framework 4.5")
    SystemDb(internet_bank_db, "БД интернет-банка", "MS SQL")
    SystemQueue(q_new_deposits, "Очередь новых заявок на депозиты", "Apache Kafka")
    SystemQueue(q_approved_new_deposits, "Очередь сообщений для подтвержденных клиентом заявок на создание депозита", "Apache Kafka")
    SystemQueue(q_all_deposits, "Очередь сообщений для доступных депозитов", "Apache Kafka")
    Container(srv_new_deposits, "Микросервис новых заявок на открытие депозитов", "Java Spring Boot")
    SystemDb(abs_db, "База данных автоматизированной банковской системы (АБС)", "Oracle")
    Container(abs, "Автоматизированная банковская система (АБС)", "Delphi")
}

' Работа со списком доступных депозитов для открытия
Rel(client, internet_bank, "Получение списка доступных депозитов")
Rel(internet_bank, internet_bank_db, "Список доступных депозитов для открытия клиентом")
Rel(abs_db, q_all_deposits, "Доступные депозиты")
Rel(q_all_deposits, internet_bank_db, "Обновление информации о доступных депозитах")

' Клиент создает заявку на открытие депозита
Rel(client, internet_bank, "Подача заявки на открытие депозита")
Rel(internet_bank, q_new_deposits, "Заявка на открытие депозита")
Rel(q_new_deposits, srv_new_deposits, "Заявки на открытие депозитов")
Rel(srv_new_deposits, telecomOperator, "Отправка одноразового СМС-кода с подтверждением создания заявки")\

' Клиент подтвердил заявку на открытие депозита
Rel(srv_new_deposits, q_approved_new_deposits, "Подтвержденные заявки на создание депозитов")
Rel(q_approved_new_deposits, abs_db, "Подтвержденные заявки на создание депозитов")
Rel(abs_db, abs, "Заявки на создание депозитов")
Rel(back_employee, abs, "Утверждение или отклонение новых заявок на создание депозитов")
Rel(abs, telecomOperator, "СМС-уведомление клиента об утверждение или отклонение создания депозита")

@enduml
